version: 2.1

defdocker: &defdocker 
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defdocker
    steps:
      - checkout 
      - run: npm install
      - run: npm run lint
  test:
    <<: *defdocker
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  analyse:
    <<: *defdocker
    steps:
      - checkout
      - run: npm audit

workflows:
  build_test_analyse:
    jobs:
      - build
      - test:
          requires: 
            - build
      - analyse:
          requires: 
            - test
      
